name: Publish to NuGet

on:
  push:
    branches: main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - run: dotnet tool install -g gitversion.tool --version 5.10.3
      - run: git rev-parse --is-shallow-repository || git fetch --unshallow
      - run: dotnet-gitversion -showvariable NuGetVersion
        name: Debug - check if gitversion works
      - run: VERSION=$(dotnet-gitversion -showvariable NuGetVersion)
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test
      - run: dotnet pack -c Release -p:Version=$(VERSION)