name: Publish to NuGet

on:
  push:
    branches: main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - run: dotnet tool install -g gitversion.tool --version 5.10.3
      - run: echo "VERSION=$(dotnet-gitversion -showvariable NuGetVersion)" >> $GITHUB_ENV
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test
      - run: dotnet pack -c Release -p:PackageVersion=$(VERSION)